.TH "notunes" "" "August 2013" "" ""
.SH "NAME"
\fBnotunes\fR
.P
iTunes CLI for Mac OS
.SH Getting Started
.P
Install with: \fBnpm install notunes \-g\fR
.SH Documentation
.P
\fBnotunes\fR or \fBman notunes\fR
.P
  Usage: notunes [options] [command]
.P
  Commands:
.P
.RS 2
.EX
play                   Play Music

pause                  Pause Music

toggle                 Play or Pause

next                   Next Track

previous               Previous Track

stop                   Stop Music
.EE
.RE
.P
  Options:
.P
.RS 2
.EX
\-h, \-\-help     output usage information

\-V, \-\-version  output the version number
.EE
.RE
.SH Examples
.P
\fI(Coming soon)\fR
.SH Contributing
.P
In lieu of a formal styleguide, take care to maintain the existing coding style\. Add unit tests for any new or changed functionality\. Lint and test your code using Grunt \fIhttp://gruntjs\.com/\fR\|\.
.SH Release History
.P
\fI(Nothing yet)\fR
.SH License
.P
Copyright (c) 2013 shawjia
Licensed under the MIT license\.

